name: docrag-cpu
channels:
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - pip
  - jupyter
  - faiss-cpu=1.11.0
  - ipykernel
  - python=3.12
  - scikit-learn
